FROM caddy:builder-alpine AS builder

RUN xcaddy build \
    --with github.com/WeidiDeng/caddy-cloudflare-ip \
    --with github.com/caddyserver/transform-encoder

FROM caddy:latest-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
